---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wg-easy
  namespace: wg-easy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app :
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: 15@sha256:4ffc03c35dce5456bbb2fa6b136a1eeb196394548dee0650ae692efdd1062e01
            env:
              LANG: EN
              WG_HOST: vpn.kharnox.com
              PORT: &uiPort 51822
              WG_PORT: &wgPort 51821
              WG_DEFAULT_DNS: 192.168.129.200
              WG_MTU: 1280
              WG_PERSISTENT_KEEPALIVE: 25
              WG_ALLOWED_IPS: 0.0.0.0/0
              UI_TRAFFIC_STATS: "true"
              UI_CHART_TYPE: 1
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - NET_ADMIN
                  # - SYS_MODULE
                  - NET_RAW
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
    service:
      ui:
        controller: main
        primary: true
        ports:
          http:
            port: *uiPort
      wg:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 192.168.129.199
        ports:
          vpn:
            targetPort: *wgPort
            port: 31821
            protocol: UDP

    route:
      ui:
        hostnames:
          - "wg.kharnox.com"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-wg
        rules:
          - backendRefs:
              - identifier: ui
                port: *uiPort
    persistence:
      config:
        enabled: true
        existingClaim: wg-easy-config
        globalMounts:
          - path: /config
